### ISSUE TITLE
MDX integration imports all providers

### ISSUE THREAD

**Issue by sylvinus** [delucis/astro-embed#134] opened 2024-07-09 14:59 UTC
When using the MDX auto-imports, all embeds CSS files are loaded (YT, vimeo, ...), not just the one being used.

It seems to be the same behaviour that the "standalone installation" fixes:
https://astro-embed.netlify.app/components/youtube/#standalone-installation

It might be better to switch the auto-import method here to use standalone installs instead?
https://github.com/delucis/astro-embed/blob/96ce82eef9ccbcf228ad2e589d066974899e805f/packages/astro-embed-integration/index.ts#L40

**Comment by delucis** [comment] 2024-07-31 17:09
Thanks @sylvinus — closing this as a duplicate of https://github.com/delucis/astro-auto-import/issues/43

**Closed by delucis** 2024-07-31 17:09 UTC
